spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  periodo-academico-actual: ${PERIODO_ACTUAL}
  iqtest:
    session-attr: cif
    dev-cif: ${DEV_CIF:UNUSED}
  integracion:
    token: ${INTEGRACION_TOKEN}
