spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  periodo-academico-actual: ${PERIODO_ACTUAL}
  imagenes:
    base-url: ${IMAGENES_BASE_URL}
    upload-dir: ${IMAGENES_UPLOAD_DIR}
  iqtest:
    session-attr: cif
    dev-cif: ${DEV_CIF:UNUSED}
  integracion:
    api-key: ${INTEGRACION_API_KEY}
