-- Create usuario table for RF-ESP-26 database-backed users
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true
);

-- Seed default users with BCrypt strength 12 hashes
INSERT INTO usuario (username, password, rol, activo) VALUES
  ('admin', '$2a$12$Y0Ikaw.8odPVLIdCkvkL1.nga/owWpLPgxA8BKxrgcFAKwiXO1Jx2', 'ROLE_ADMIN', true),
  ('evaluador', '$2a$12$/Hnh0GUcoHHwhu/ODYq6YuSxtBzOEVAQTtndDiL1NSuiyz9VjWQ5G', 'ROLE_EVALUADOR', true),
  ('estudiante', '$2a$12$KXXLvKTdNiMGsCn7h3mNyOeyRiHjDay1v8cT7PqbGYDLl5BVtKgdK', 'ROLE_ESTUDIANTE', true);

-- Add column for internal consistency / pattern alerts (RF-ESP-22 / BR-14)
ALTER TABLE resultado ADD COLUMN alerta_consistencia VARCHAR(255);
