-- Seed one active VersionFormulario for 2026
INSERT INTO version_formulario (id, anio, numero_version, activa) OVERRIDING SYSTEM VALUE VALUES (1, 2026, 1, true);

-- Seed S1A items
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (1, 1, 'S1A', 1, '/img/s1a/item_1.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (1, 1, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (2, 1, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (3, 1, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (4, 1, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (5, 1, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (2, 1, 'S1A', 2, '/img/s1a/item_2.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (6, 2, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (7, 2, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (8, 2, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (9, 2, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (10, 2, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (3, 1, 'S1A', 3, '/img/s1a/item_3.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (11, 3, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (12, 3, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (13, 3, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (14, 3, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (15, 3, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (4, 1, 'S1A', 4, '/img/s1a/item_4.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (16, 4, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (17, 4, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (18, 4, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (19, 4, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (20, 4, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (5, 1, 'S1A', 5, '/img/s1a/item_5.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (21, 5, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (22, 5, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (23, 5, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (24, 5, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (25, 5, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (6, 1, 'S1A', 6, '/img/s1a/item_6.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (26, 6, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (27, 6, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (28, 6, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (29, 6, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (30, 6, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (7, 1, 'S1A', 7, '/img/s1a/item_7.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (31, 7, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (32, 7, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (33, 7, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (34, 7, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (35, 7, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (8, 1, 'S1A', 8, '/img/s1a/item_8.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (36, 8, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (37, 8, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (38, 8, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (39, 8, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (40, 8, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (9, 1, 'S1A', 9, '/img/s1a/item_9.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (41, 9, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (42, 9, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (43, 9, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (44, 9, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (45, 9, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (10, 1, 'S1A', 10, '/img/s1a/item_10.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (46, 10, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (47, 10, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (48, 10, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (49, 10, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (50, 10, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (11, 1, 'S1A', 11, '/img/s1a/item_11.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (51, 11, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (52, 11, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (53, 11, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (54, 11, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (55, 11, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (12, 1, 'S1A', 12, '/img/s1a/item_12.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (56, 12, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (57, 12, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (58, 12, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (59, 12, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (60, 12, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (13, 1, 'S1A', 13, '/img/s1a/item_13.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (61, 13, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (62, 13, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (63, 13, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (64, 13, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (65, 13, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (14, 1, 'S1A', 14, '/img/s1a/item_14.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (66, 14, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (67, 14, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (68, 14, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (69, 14, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (70, 14, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (15, 1, 'S1A', 15, '/img/s1a/item_15.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (71, 15, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (72, 15, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (73, 15, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (74, 15, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (75, 15, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (16, 1, 'S1A', 16, '/img/s1a/item_16.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (76, 16, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (77, 16, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (78, 16, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (79, 16, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (80, 16, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (17, 1, 'S1A', 17, '/img/s1a/item_17.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (81, 17, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (82, 17, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (83, 17, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (84, 17, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (85, 17, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (18, 1, 'S1A', 18, '/img/s1a/item_18.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (86, 18, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (87, 18, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (88, 18, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (89, 18, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (90, 18, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (19, 1, 'S1A', 19, '/img/s1a/item_19.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (91, 19, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (92, 19, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (93, 19, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (94, 19, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (95, 19, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (20, 1, 'S1A', 20, '/img/s1a/item_20.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (96, 20, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (97, 20, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (98, 20, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (99, 20, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (100, 20, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (21, 1, 'S1A', 21, '/img/s1a/item_21.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (101, 21, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (102, 21, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (103, 21, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (104, 21, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (105, 21, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (22, 1, 'S1A', 22, '/img/s1a/item_22.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (106, 22, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (107, 22, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (108, 22, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (109, 22, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (110, 22, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (23, 1, 'S1A', 23, '/img/s1a/item_23.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (111, 23, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (112, 23, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (113, 23, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (114, 23, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (115, 23, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (24, 1, 'S1A', 24, '/img/s1a/item_24.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (116, 24, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (117, 24, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (118, 24, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (119, 24, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (120, 24, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (25, 1, 'S1A', 25, '/img/s1a/item_25.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (121, 25, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (122, 25, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (123, 25, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (124, 25, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (125, 25, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (26, 1, 'S1A', 26, '/img/s1a/item_26.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (126, 26, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (127, 26, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (128, 26, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (129, 26, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (130, 26, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (27, 1, 'S1A', 27, '/img/s1a/item_27.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (131, 27, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (132, 27, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (133, 27, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (134, 27, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (135, 27, 'E', false);

-- Seed S2 items
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (28, 1, 'S2', 1, '/img/s2/item_1.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (136, 28, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (137, 28, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (138, 28, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (139, 28, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (140, 28, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (29, 1, 'S2', 2, '/img/s2/item_2.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (141, 29, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (142, 29, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (143, 29, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (144, 29, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (145, 29, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (30, 1, 'S2', 3, '/img/s2/item_3.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (146, 30, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (147, 30, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (148, 30, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (149, 30, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (150, 30, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (31, 1, 'S2', 4, '/img/s2/item_4.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (151, 31, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (152, 31, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (153, 31, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (154, 31, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (155, 31, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (32, 1, 'S2', 5, '/img/s2/item_5.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (156, 32, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (157, 32, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (158, 32, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (159, 32, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (160, 32, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (33, 1, 'S2', 6, '/img/s2/item_6.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (161, 33, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (162, 33, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (163, 33, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (164, 33, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (165, 33, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (34, 1, 'S2', 7, '/img/s2/item_7.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (166, 34, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (167, 34, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (168, 34, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (169, 34, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (170, 34, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (35, 1, 'S2', 8, '/img/s2/item_8.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (171, 35, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (172, 35, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (173, 35, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (174, 35, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (175, 35, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (36, 1, 'S2', 9, '/img/s2/item_9.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (176, 36, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (177, 36, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (178, 36, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (179, 36, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (180, 36, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (37, 1, 'S2', 10, '/img/s2/item_10.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (181, 37, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (182, 37, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (183, 37, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (184, 37, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (185, 37, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (38, 1, 'S2', 11, '/img/s2/item_11.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (186, 38, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (187, 38, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (188, 38, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (189, 38, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (190, 38, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (39, 1, 'S2', 12, '/img/s2/item_12.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (191, 39, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (192, 39, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (193, 39, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (194, 39, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (195, 39, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (40, 1, 'S2', 13, '/img/s2/item_13.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (196, 40, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (197, 40, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (198, 40, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (199, 40, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (200, 40, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (41, 1, 'S2', 14, '/img/s2/item_14.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (201, 41, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (202, 41, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (203, 41, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (204, 41, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (205, 41, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (42, 1, 'S2', 15, '/img/s2/item_15.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (206, 42, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (207, 42, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (208, 42, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (209, 42, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (210, 42, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (43, 1, 'S2', 16, '/img/s2/item_16.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (211, 43, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (212, 43, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (213, 43, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (214, 43, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (215, 43, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (44, 1, 'S2', 17, '/img/s2/item_17.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (216, 44, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (217, 44, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (218, 44, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (219, 44, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (220, 44, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (45, 1, 'S2', 18, '/img/s2/item_18.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (221, 45, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (222, 45, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (223, 45, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (224, 45, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (225, 45, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (46, 1, 'S2', 19, '/img/s2/item_19.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (226, 46, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (227, 46, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (228, 46, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (229, 46, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (230, 46, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (47, 1, 'S2', 20, '/img/s2/item_20.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (231, 47, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (232, 47, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (233, 47, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (234, 47, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (235, 47, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (48, 1, 'S2', 21, '/img/s2/item_21.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (236, 48, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (237, 48, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (238, 48, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (239, 48, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (240, 48, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (49, 1, 'S2', 22, '/img/s2/item_22.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (241, 49, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (242, 49, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (243, 49, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (244, 49, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (245, 49, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (50, 1, 'S2', 23, '/img/s2/item_23.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (246, 50, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (247, 50, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (248, 50, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (249, 50, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (250, 50, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (51, 1, 'S2', 24, '/img/s2/item_24.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (251, 51, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (252, 51, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (253, 51, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (254, 51, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (255, 51, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (52, 1, 'S2', 25, '/img/s2/item_25.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (256, 52, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (257, 52, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (258, 52, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (259, 52, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (260, 52, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (53, 1, 'S2', 26, '/img/s2/item_26.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (261, 53, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (262, 53, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (263, 53, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (264, 53, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (265, 53, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (54, 1, 'S2', 27, '/img/s2/item_27.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (266, 54, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (267, 54, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (268, 54, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (269, 54, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (270, 54, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (55, 1, 'S2', 28, '/img/s2/item_28.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (271, 55, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (272, 55, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (273, 55, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (274, 55, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (275, 55, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (56, 1, 'S2', 29, '/img/s2/item_29.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (276, 56, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (277, 56, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (278, 56, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (279, 56, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (280, 56, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (57, 1, 'S2', 30, '/img/s2/item_30.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (281, 57, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (282, 57, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (283, 57, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (284, 57, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (285, 57, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (58, 1, 'S2', 31, '/img/s2/item_31.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (286, 58, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (287, 58, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (288, 58, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (289, 58, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (290, 58, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (59, 1, 'S2', 32, '/img/s2/item_32.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (291, 59, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (292, 59, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (293, 59, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (294, 59, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (295, 59, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (60, 1, 'S2', 33, '/img/s2/item_33.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (296, 60, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (297, 60, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (298, 60, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (299, 60, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (300, 60, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (61, 1, 'S2', 34, '/img/s2/item_34.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (301, 61, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (302, 61, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (303, 61, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (304, 61, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (305, 61, 'E', false);

-- Seed S1B items
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (62, 1, 'S1B', 1, '/img/s1b/item_1.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (306, 62, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (307, 62, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (308, 62, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (309, 62, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (310, 62, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (63, 1, 'S1B', 2, '/img/s1b/item_2.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (311, 63, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (312, 63, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (313, 63, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (314, 63, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (315, 63, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (64, 1, 'S1B', 3, '/img/s1b/item_3.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (316, 64, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (317, 64, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (318, 64, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (319, 64, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (320, 64, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (65, 1, 'S1B', 4, '/img/s1b/item_4.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (321, 65, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (322, 65, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (323, 65, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (324, 65, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (325, 65, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (66, 1, 'S1B', 5, '/img/s1b/item_5.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (326, 66, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (327, 66, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (328, 66, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (329, 66, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (330, 66, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (67, 1, 'S1B', 6, '/img/s1b/item_6.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (331, 67, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (332, 67, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (333, 67, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (334, 67, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (335, 67, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (68, 1, 'S1B', 7, '/img/s1b/item_7.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (336, 68, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (337, 68, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (338, 68, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (339, 68, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (340, 68, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (69, 1, 'S1B', 8, '/img/s1b/item_8.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (341, 69, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (342, 69, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (343, 69, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (344, 69, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (345, 69, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (70, 1, 'S1B', 9, '/img/s1b/item_9.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (346, 70, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (347, 70, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (348, 70, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (349, 70, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (350, 70, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (71, 1, 'S1B', 10, '/img/s1b/item_10.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (351, 71, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (352, 71, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (353, 71, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (354, 71, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (355, 71, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (72, 1, 'S1B', 11, '/img/s1b/item_11.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (356, 72, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (357, 72, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (358, 72, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (359, 72, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (360, 72, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (73, 1, 'S1B', 12, '/img/s1b/item_12.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (361, 73, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (362, 73, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (363, 73, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (364, 73, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (365, 73, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (74, 1, 'S1B', 13, '/img/s1b/item_13.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (366, 74, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (367, 74, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (368, 74, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (369, 74, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (370, 74, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (75, 1, 'S1B', 14, '/img/s1b/item_14.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (371, 75, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (372, 75, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (373, 75, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (374, 75, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (375, 75, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (76, 1, 'S1B', 15, '/img/s1b/item_15.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (376, 76, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (377, 76, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (378, 76, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (379, 76, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (380, 76, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (77, 1, 'S1B', 16, '/img/s1b/item_16.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (381, 77, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (382, 77, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (383, 77, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (384, 77, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (385, 77, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (78, 1, 'S1B', 17, '/img/s1b/item_17.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (386, 78, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (387, 78, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (388, 78, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (389, 78, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (390, 78, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (79, 1, 'S1B', 18, '/img/s1b/item_18.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (391, 79, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (392, 79, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (393, 79, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (394, 79, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (395, 79, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (80, 1, 'S1B', 19, '/img/s1b/item_19.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (396, 80, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (397, 80, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (398, 80, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (399, 80, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (400, 80, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (81, 1, 'S1B', 20, '/img/s1b/item_20.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (401, 81, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (402, 81, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (403, 81, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (404, 81, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (405, 81, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (82, 1, 'S1B', 21, '/img/s1b/item_21.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (406, 82, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (407, 82, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (408, 82, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (409, 82, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (410, 82, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (83, 1, 'S1B', 22, '/img/s1b/item_22.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (411, 83, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (412, 83, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (413, 83, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (414, 83, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (415, 83, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (84, 1, 'S1B', 23, '/img/s1b/item_23.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (416, 84, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (417, 84, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (418, 84, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (419, 84, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (420, 84, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (85, 1, 'S1B', 24, '/img/s1b/item_24.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (421, 85, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (422, 85, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (423, 85, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (424, 85, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (425, 85, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (86, 1, 'S1B', 25, '/img/s1b/item_25.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (426, 86, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (427, 86, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (428, 86, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (429, 86, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (430, 86, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (87, 1, 'S1B', 26, '/img/s1b/item_26.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (431, 87, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (432, 87, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (433, 87, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (434, 87, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (435, 87, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (88, 1, 'S1B', 27, '/img/s1b/item_27.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (436, 88, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (437, 88, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (438, 88, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (439, 88, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (440, 88, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (89, 1, 'S1B', 28, '/img/s1b/item_28.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (441, 89, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (442, 89, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (443, 89, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (444, 89, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (445, 89, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (90, 1, 'S1B', 29, '/img/s1b/item_29.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (446, 90, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (447, 90, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (448, 90, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (449, 90, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (450, 90, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (91, 1, 'S1B', 30, '/img/s1b/item_30.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (451, 91, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (452, 91, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (453, 91, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (454, 91, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (455, 91, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (92, 1, 'S1B', 31, '/img/s1b/item_31.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (456, 92, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (457, 92, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (458, 92, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (459, 92, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (460, 92, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (93, 1, 'S1B', 32, '/img/s1b/item_32.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (461, 93, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (462, 93, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (463, 93, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (464, 93, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (465, 93, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (94, 1, 'S1B', 33, '/img/s1b/item_33.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (466, 94, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (467, 94, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (468, 94, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (469, 94, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (470, 94, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (95, 1, 'S1B', 34, '/img/s1b/item_34.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (471, 95, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (472, 95, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (473, 95, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (474, 95, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (475, 95, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (96, 1, 'S1B', 35, '/img/s1b/item_35.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (476, 96, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (477, 96, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (478, 96, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (479, 96, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (480, 96, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (97, 1, 'S1B', 36, '/img/s1b/item_36.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (481, 97, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (482, 97, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (483, 97, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (484, 97, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (485, 97, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (98, 1, 'S1B', 37, '/img/s1b/item_37.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (486, 98, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (487, 98, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (488, 98, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (489, 98, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (490, 98, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (99, 1, 'S1B', 38, '/img/s1b/item_38.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (491, 99, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (492, 99, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (493, 99, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (494, 99, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (495, 99, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (100, 1, 'S1B', 39, '/img/s1b/item_39.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (496, 100, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (497, 100, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (498, 100, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (499, 100, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (500, 100, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (101, 1, 'S1B', 40, '/img/s1b/item_40.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (501, 101, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (502, 101, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (503, 101, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (504, 101, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (505, 101, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (102, 1, 'S1B', 41, '/img/s1b/item_41.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (506, 102, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (507, 102, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (508, 102, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (509, 102, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (510, 102, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (103, 1, 'S1B', 42, '/img/s1b/item_42.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (511, 103, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (512, 103, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (513, 103, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (514, 103, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (515, 103, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (104, 1, 'S1B', 43, '/img/s1b/item_43.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (516, 104, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (517, 104, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (518, 104, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (519, 104, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (520, 104, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (105, 1, 'S1B', 44, '/img/s1b/item_44.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (521, 105, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (522, 105, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (523, 105, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (524, 105, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (525, 105, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (106, 1, 'S1B', 45, '/img/s1b/item_45.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (526, 106, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (527, 106, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (528, 106, 'C', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (529, 106, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (530, 106, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (107, 1, 'S1B', 46, '/img/s1b/item_46.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (531, 107, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (532, 107, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (533, 107, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (534, 107, 'D', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (535, 107, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (108, 1, 'S1B', 47, '/img/s1b/item_47.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (536, 108, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (537, 108, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (538, 108, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (539, 108, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (540, 108, 'E', true);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (109, 1, 'S1B', 48, '/img/s1b/item_48.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (541, 109, 'A', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (542, 109, 'B', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (543, 109, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (544, 109, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (545, 109, 'E', false);
INSERT INTO reactivo (id, version_formulario_id, tipo_subtest, orden, enunciado_imagen_url, enunciado_texto, activo) OVERRIDING SYSTEM VALUE VALUES (110, 1, 'S1B', 49, '/img/s1b/item_49.png', '', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (546, 110, 'A', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (547, 110, 'B', true);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (548, 110, 'C', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (549, 110, 'D', false);
INSERT INTO opcion_reactivo (id, reactivo_id, etiqueta, es_correcta) OVERRIDING SYSTEM VALUE VALUES (550, 110, 'E', false);

SELECT setval('version_formulario_id_seq', (SELECT MAX(id) FROM version_formulario));
SELECT setval('reactivo_id_seq', (SELECT MAX(id) FROM reactivo));
SELECT setval('opcion_reactivo_id_seq', (SELECT MAX(id) FROM opcion_reactivo));
